<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Band extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
    ];

    public function user()
    {
        $this->belongsTo(User::class);
    }

    public function moderator()
    {
        return $this->belongsToMany(Moderator::class);
    }

    public function bandBio()
    {
        return $this->hasOne(BandBio::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($band) {
            $band->bio()->create([]);
        });
    }

}
